### ISSUE TITLE
dependencies conflicting with postgres-dev dependencies

### ISSUE THREAD

**Issue by Primital** [jazzband/django-rest-knox#170]
Cryptography (2.5) depends on OpenSSL, however postgres-dev depends on libressl.

>ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2q-r0:
    conflicts:
               libressl-dev-2.6.5-r0[pc:libcrypto=1.0.2q]
               libressl-dev-2.6.5-r0[pc:libssl=1.0.2q]
               libressl-dev-2.6.5-r0[pc:openssl=1.0.2q]
    satisfies: world[openssl-dev]
  libressl-dev-2.6.5-r0:
    conflicts:
               openssl-dev-1.0.2q-r0[pc:libcrypto=2.6.5]
               openssl-dev-1.0.2q-r0[pc:libssl=2.6.5]
               openssl-dev-1.0.2q-r0[pc:openssl=2.6.5]

**Comment by johnraz** [comment]
There seem to be a long thread on https://github.com/pyca/cryptography/issues/4264 discussing this.

How would you expect us to address this, I'm not quite sure how we can fix this?

@James1345 I may need some insight from you here as the use of pyOpenSSL seems to have been discussed quite a lot since the library's born.

Cheers.

**Comment by Primital** [comment]
@johnraz Thank you for the link.
My purpose was just to highlight the issue, since it is not possible currently to run docker + DRF + postgres + knox with this dependency.

Perhaps it's possible to fork the repo and replace openSSL functions with libressl functions, but I haven't the time nor the expertise to do that myself.

**Comment by johnraz** [comment]
cryptography is not used anymore
