### ISSUE TITLE
Issuing Token outside of LoginView

### ISSUE THREAD

**Issue by HasanAshab** [jazzband/django-rest-knox#334]
Is there any way to create token outside of LoginView. 

There is a method **create_token** in LoginView
```python
def create_token(self):
        token_prefix = self.get_token_prefix()
        return get_token_model().objects.create(
            user=self.request.user, expiry=self.get_token_ttl(), prefix=token_prefix
        )
```
but, it may be more concise to have a function like **create_token(user)**.

Thanks in advance!

**Comment by johnraz** [comment]
Well, the manager method above ( https://github.com/jazzband/django-rest-knox/blob/09403255a069c2416a5dfb889f80342a2d7b2646/knox/models.py#L16 ) is the way to create a token, you can access prefix and ttl from the settings. They are proxied by methods in the LoginView in order to be easily overridden.

I don’t think anything is missing.
